### Register new user
POST https://eduzzleapp-react-native.onrender.com/api/auth/register
Content-Type: application/json

{
  "name": "Abhishek Yadav",
  "email": "abhishekydv2408@gmail.com",
  "password": "User@#123"
}





