### Upload Profile Picture
PUT https://eduzzleapp-react-native.onrender.com/api/user/profile-pic
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Zjc5ZmMxYmExNWJjMmNlNTAzMzIzOSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzYxNDA0NjkyLCJleHAiOjE3NjIwMDk0OTJ9.2K73pzBa2UQUL_xOuslyi82PCDayJZ1p8LuE-Y0q-Dk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="profilePic"; filename="sample.jpg"
Content-Type: image/jpeg

< ./sample.jpg
--WebAppBoundary--
